### ISSUE TITLE
Inability to parameterize InfluxDB queries

### ISSUE THREAD

**Issue by MarcoAmato** [smolang/SemanticObjects#21]
I am unable to parameterize InfluxDB queries when using SMOL. This limits the flexibility and reusability of queries. It would be helpful if there was a way to include parameters in InfluxDB queries when calling them from SMOL.

**Comment by Edkamb** [comment]
Please check your program with 4b7e745 and close this ticket if it works.

**Comment by N-essuno** [comment]
Now the influx query works with String parameters but it throws an error (probably an influxdb syntax error) if we try to parameterize with Integers.

Query we run:
```
Double getMeanMoisture(Int shelfFloor, String groupPosition, String potPosition)
    meanMoistureList = access(
            "from(bucket: \"greenhouse_test\")
                |> range(start: -30d)
                |> filter(fn: (r) => r[\"_measurement\"] == \"ast:pot\")
                |> filter(fn: (r) => r[\"_field\"] == \"moisture\")
                |> filter(fn: (r) => r[\"group_position\"] == %1)
                |> filter(fn: (r) => r[\"pot_position\"] == %2)
                |> filter(fn: (r) => r[\"shelf_floor\"] == %3)
                |> keep(columns: [\"_value\"])
                |> mean(column: \"_value\")",
            INFLUXDB("config_local.yml"), groupPosition, potPosition, shelfFloor);
end
```

Error we got:
```
com.influxdb.exceptions.BadRequestException: compilation failed: error @7:16-7:71: expected comma in property list, got COLON

error @7:58-7:59: invalid expression: invalid token for primary expression: POW

error @7:62-7:70: missing property key
        at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:96)
        at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:211)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Edkamb** [comment]
Please try again, I forgot to remove the RDF annotations

**Comment by N-essuno** [comment]
Parameterizing on Influx queries now works. I opened another issue related to the parameterization (#28) but I think this can be closed.
