### ISSUE TITLE
Primitive types conversion problem for parameters in InfluxDB queries

### ISSUE THREAD

**Issue by N-essuno** [smolang/SemanticObjects#28]
I have an Integer variable `a` but I need the String version to pass it as parameter in InfluxDB queries.
When I try to convert `a` to String using `String b = intToString(a)` and pass `b` as parameter for an influxDB query it throws an exception (related to the fact that the query fails and so the list that should contain the query result cannot be accessed). E.g:

Running the following code (excerpt from a program):
```
main
  String groupPosition = "left";
  String potPosition = "right";
  Double meanMoisture = 0.0;
  List<Double> meanMoistureList = null;
  Int shelfFloor = 1;

  String shelfFloorString = intToString(shelfFloor);
  print(shelfFloor);
  print (shelfFloorString);
  
  meanMoistureList = access(
      "from(bucket: \"greenhouse_test\")
          |> range(start: -30d)
          |> filter(fn: (r) => r[\"_measurement\"] == \"ast:pot\")
          |> filter(fn: (r) => r[\"_field\"] == \"moisture\")
          |> filter(fn: (r) => r[\"group_position\"] == %1)
          |> filter(fn: (r) => r[\"pot_position\"] == %2)
          |> filter(fn: (r) => r[\"shelf_floor\"] == %3)
          |> keep(columns: [\"_value\"])
          |> mean(column: \"_value\")",
      INFLUXDB("config_local.yml"), groupPosition, potPosition, shelfFloorString);
  
  meanMoisture = meanMoistureList.get(0);
  print("mean moisture:");
  print(meanMoisture);
end
```

throws the following error:
```
java.lang.Exception: This class is unknown: ERROR when executing meanMoisture := meanMoistureList.get(0) at l. pos
        at no.uio.microobject.ast.stmt.CallStmt.eval(CallStmt.kt:34)
        at no.uio.microobject.ast.stmt.SequenceStmt.eval(SequenceStmt.kt:26)
        at no.uio.microobject.runtime.Interpreter.makeStep(Interpreter.kt:170)
        at no.uio.microobject.runtime.REPL$initCommands$3.invoke(REPL.kt:145)
        at no.uio.microobject.runtime.REPL$initCommands$3.invoke(REPL.kt:142)
        at no.uio.microobject.runtime.Command.execute(REPL.kt:36)
        at no.uio.microobject.runtime.REPL.command(REPL.kt:72)
        at no.uio.microobject.main.Main.run(MainKt.kt:130)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:393)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:390)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:408)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:433)
        at no.uio.microobject.main.MainKtKt.main(MainKt.kt:138)
```

same exception as running the following query (note that the parameter shelfFloorString in the influx query now is replaced with the Integer variable shelfFloor)

```
Int shelfFloor = 1;
meanMoistureList = access(
    "from(bucket: \"greenhouse_test\")
        |> range(start: -30d)
        |> filter(fn: (r) => r[\"_measurement\"] == \"ast:pot\")
        |> filter(fn: (r) => r[\"_field\"] == \"moisture\")
        |> filter(fn: (r) => r[\"group_position\"] == %1)
        |> filter(fn: (r) => r[\"pot_position\"] == %2)
        |> filter(fn: (r) => r[\"shelf_floor\"] == %3)
        |> keep(columns: [\"_value\"])
        |> mean(column: \"_value\")",
    INFLUXDB("config_local.yml"), groupPosition, potPosition, shelfFloor);
```

**Comment by Edkamb** [comment]
Seems to be closed, please reopen if any old code is still broken
